### ISSUE TITLE
白金事件导致鬼打墙

### ISSUE THREAD

**Issue by Ailencemare** [Godofcong-1/erArk#101]
[000]接住白金的衣服
[001]帮白金整理好衣服
[000]负起责任
[001]麻烦白金忍耐
会在睡觉结算时出现上述选项并形成鬼打墙导致游戏崩溃
疑似跟临产有关
[error.log](https://github.com/user-attachments/files/18063890/error.log)

**Comment by Godofcong-1** [comment]
> [000]接住白金的衣服 [001]帮白金整理好衣服 [000]负起责任 [001]麻烦白金忍耐 会在睡觉结算时出现上述选项并形成鬼打墙导致游戏崩溃 疑似跟临产有关 [error.log](https://github.com/user-attachments/files/18063890/error.log)

感谢反馈，已传达给白金口上作者，现阶段先临时ban掉部分事件，等待口上作者修复后恢复

**Comment by Godofcong-1** [comment]
12.12版本白金作者已更新相关事件，对该问题进行修复

**Comment by Godofcong-1** [comment]
因较长时间没有活跃了，所以将该issus暂时关闭，如果还有问题欢迎随时再打开
