### ISSUE TITLE
一个显示错误

### ISSUE THREAD

**Issue by bakamaigo** [Godofcong-1/erArk#21]
![QQ截图20231129210651](https://github.com/Godofcong-1/erArk/assets/38009021/1e864897-bb6b-4b44-a536-9bec39856097)
如图，刚进游戏就3个高光，还没开始玩

顺便问问，这不找点苦力写口上（）

**Comment by q547165485** [comment]
点击了一下明白是什么意思了，建议换一种表达方式，比如说指针指上去不要让它有变化

**Comment by Godofcong-1** [comment]
唔姆，姑且从默认高光改成橙色来表示选中了，新版本（11/30）已经推送了。
口上的话，打算是预订在年底发布α版时开始抓苦力，如果你有兴趣或者有苦力的话也可以现在开始。以及写的话，可以直接用推送里的口上事件编辑器来写口上
