### ISSUE TITLE
Error - 死循环

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#25]
由罗德岛出口前往控制中枢后返回博士房间进入死循环
无崩溃报告

**Comment by TheXeler** [comment]
[0.zip](https://github.com/Godofcong-1/erArk/files/13798260/0.zip)
对应存档

**Comment by TheXeler** [comment]
追加，其他位置返回博士房间也观测到类似情况

**Comment by Godofcong-1** [comment]
感谢反馈，经检查发现，在特殊情况下，如果角色已经在目标地点角色列表中，但位置并没有被移动到目标地点时会产生该死循环，已修复
目前汇报的四个BUG均已修复，新版本已推送
