### ISSUE TITLE
Error - 返回博士房间睡觉后可以反复诊疗病人至负数（妙手回春啊大夫）

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#30]
无崩溃日志
复现存档：
[5.zip](https://github.com/Godofcong-1/erArk/files/13800043/5.zip)
复现步骤：移动>查看上级地图>医疗部>移动>门诊室>诊疗病人（循环至清空）>移动>查看上级地图>博士房间>睡觉>确认>移动>查看上级地图>医疗部>移动>门诊室>诊疗病人

**Comment by Godofcong-1** [comment]
感谢反馈，已将该指令限制为只有在有病人的情况下才可以使用，且增加了该指令使用时的提示信息
目前汇报的五个BUG均已修正，新版本已推送，昨天的四个BUG的issues我也一并关闭了
