### ISSUE TITLE
Crash - package.json导致的崩溃

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#31]
无崩溃报告
无复现存档
复现方式：用新的package.json启动游戏
附注：我这算不算Issues轰炸了，还有这个崩溃好难截图的
附录： 
![图片](https://github.com/Godofcong-1/erArk/assets/14292550/f4426b6c-0a89-43e3-8ff9-6f24f400dd32)

**Comment by Godofcong-1** [comment]
感谢反馈，原因是系统上gbk编码和utf8编码的冲突问题，已推送新的package.json
附注：非常欢迎提BUG (*｀∀´*)ノ亻，我会努力马上修的
