### ISSUE TITLE
Error - 源石技艺相关：偷窃内裤后内裤不增长&源石技艺消除刻印后会反复出现

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#35]
无崩溃报告
复现存档：
[7.zip](https://github.com/Godofcong-1/erArk/files/13802599/7.zip)
复现方式：窃取内裤&源石技艺>消除反发刻印
附注：窃取内裤是催眠下做的，因为拿不到内裤所以消除刻印是DEBUG模式处理的。以及我唱歌真的有这么难听吗（恼），听一嗓子直接反发3，比坐大牢还猛
另，大概什么时候出后续的催眠和战斗，期待.jpg

**Comment by TheXeler** [comment]
补充：我使用DEBUG模式将反感珠清0后仍然会反复出现反发刻印，但是触发不太固定，消除了之后过了一会莫名其妙又涨回来了，至于清除反发的源石技艺本身好像更是根本不管反感珠，摸一下就又爆了

**Comment by Godofcong-1** [comment]
内裤：内裤的机制是和TW一样，偷取完内裤需要收藏起来才能用。收藏的位置是图书馆的藏品馆。看你的反馈应该是完全不知道这个机制，那大概我还是需要加个提示，引导玩家去这里
唱歌：目前设定的0级唱歌能力的话是挺难听的，原意是想让玩家去音乐室练歌，练好了再唱。可能需要加个限制，唱歌能力过低的话就二次确认要不要唱
反发：反发刻印的结算是拍脑袋定的反感、抑郁、恐怖这些状态的等级会导致反发，没和反感珠绑定。你这么一说我觉得还是绑定到珠上比较合理，那我补加一下需要有足够多的反感珠才能反发刻印
后续的催眠和战斗：各级催眠和助手性处理是目前比较优先的事项，大概这个月内会先实装其中一个。战斗的优先度比较低，主要是因为我没想到战斗系统怎么做，所以可能会很久之后等我有个好主意了再做

**Comment by TheXeler** [comment]
> 内裤：内裤的机制是和TW一样，偷取完内裤需要收藏起来才能用。收藏的位置是图书馆的藏品馆。看你的反馈应该是完全不知道这个机制，那大概我还是需要加个提示，引导玩家去这里 唱歌：目前设定的0级唱歌能力的话是挺难听的，原意是想让玩家去音乐室练歌，练好了再唱。可能需要加个限制，唱歌能力过低的话就二次确认要不要唱 反发：反发刻印的结算是拍脑袋定的反感、抑郁、恐怖这些状态的等级会导致反发，没和反感珠绑定。你这么一说我觉得还是绑定到珠上比较合理，那我补加一下需要有足够多的反感珠才能反发刻印 后续的催眠和战斗：各级催眠和助手性处理是目前比较优先的事项，大概这个月内会先实装其中一个。战斗的优先度比较低，主要是因为我没想到战斗系统怎么做，所以可能会很久之后等我有个好主意了再做

收到，另外顺便多问一个问题，我没找到该怎么使用理智液，直接在道具中点击也无效，进食也没有相关选项

**Comment by Godofcong-1** [comment]
理智液：检查了一下，确实是忘了加理智液的使用函数了，今天修一下
反发：关于反发的问题，我思考了一下，反发刻印是在指令当场触发的效果，反感珠是每日24点结算的珠子。假如说极端情况里，第一天开局还没有珠子，但是做了反发的事情，那就不应该因为没有珠子而无法触发反发刻印。
所以反发就还是按照现在的因为角色的状态值而触发，反感珠改为每天结算的时候自动抵消其他正向珠的增长
昨晚凌晨的版本：已经增加了唱歌/演奏的低等级时二次确认，也增加了窃取内裤和袜子的提示信息

**Comment by TheXeler** [comment]
> 理智液：检查了一下，确实是忘了加理智液的使用函数了，今天修一下 反发：关于反发的问题，我思考了一下，反发刻印是在指令当场触发的效果，反感珠是每日24点结算的珠子。假如说极端情况里，第一天开局还没有珠子，但是做了反发的事情，那就不应该因为没有珠子而无法触发反发刻印。 所以反发就还是按照现在的因为角色的状态值而触发，反感珠改为每天结算的时候自动抵消其他正向珠的增长 昨晚凌晨的版本：已经增加了唱歌/演奏的低等级时二次确认，也增加了窃取内裤和袜子的提示信息

主要问题是源石技艺在消除反发刻印的时候不会连状态值一并清理，而且唱歌的时候并不会提示到底是状态值还是反感珠

**Comment by TheXeler** [comment]
另外游戏中几个货币的主要入手方式最好都给点提示在普瑞赛斯里（龙门币、粉红凭证、至纯源石之类的），方便新人找

**Comment by Godofcong-1** [comment]
> 主要问题是源石技艺在消除反发刻印的时候不会连状态值一并清理，而且唱歌的时候并不会提示到底是状态值还是反感珠

有道理，那我在消反发的时候也附赠消除当前的反感状态

> 另外游戏中几个货币的主要入手方式最好都给点提示在普瑞赛斯里（龙门币、粉红凭证、至纯源石之类的），方便新人找

好，而且普瑞赛斯还有相当多需要加的，大概每个系统都得有个提示或者介绍
