### ISSUE TITLE
反馈一点问题和建议

### ISSUE THREAD

**Issue by Kamisato100** [Godofcong-1/erArk#39]
1：捏人的erArkEditor里面，如果给人物加的素质、服装和能力比较多，会导致程序窗口不断自动拉长往下顶而无法在窗口模式下点击屏幕下方的保存按钮，点击全屏化以后倒是可以保存了但是服装栏目会错位摞在一块，是否可以考虑增加一个滑动条（就像常见的网页一样，允许用滚轮上下滑动和浏览界面内的内容）？以及增加快速设置素质能力经验项目数量的选项（毕竟界面上那么一大块地方就放俩添加删除按钮也太浪费了，初次捏人得重复点击多次来增加项目数量也很麻烦）。其次是自己捏的人物需要在立绘文件夹里加一张对应名称的立绘，不然会出现报错卡死现象，这点也许可以在捏人界面写一个小提示，以免有些没注意到这个问题的人游戏卡死还不知道怎么回事。
2：是否可以考虑游戏内增加一个快速总览信息的面板？注意到游戏内目前好像只能看见当前场景下的干员信息，也就是说想看干员信息情况还得把人单独叫过来，这点上很麻烦，也许可以考虑参考其他era那样做一个能快速查看各干员当前简略信息的面板，然后点进去可以单独查看干员详细情况的功能？
3：注意到自己捏的人物是没有通用口上的，只会显示一条触发了xx口上，是哪里没设置好还是目前没有实装通用口上设置呢？
4：也许可以考虑增加一个快速度过时间的选项（比如era某N的结束这一天，或者eratw的睡觉），目前玩了一下似乎就只有在体力不足时能短暂小睡1小时，就导致想测试妊娠系统这种时间跨度比较大的功能时相当坐牢，得想方设法慢慢拖过去漫长的时间，24小时连轴转只有累的时候才睡1小时，什么超级源石超人也难顶罢（悲），如果能有一个快速结算当天情况，并且简单汇报一下关注了的干员今天大概做了啥/或者发生了什么涩涩和重要的事的功能就会舒服很多。
5：自己捏的干员AI好像还是有些问题，虽然看日程安排里有不少事情安排，但是实际观察后发现这货基本上就是每天食堂宿舍两点一线，吃了睡睡了吃，什么摆烂人日子（ ）
6：建议读写存档功能分开为两个入口，或者至少别让“读取”“覆盖”“删除”它们挨这么近，要不然已经可以预见到某时候可能因为手滑导致想读档的时候不小心把存档覆盖或者删除，想覆盖的时候点到读取这种血压拉满的情况了。
7：之前的emura有个快捷功能是往上翻阅了之前的记录之后，单击一下任意地方就可以自动回到最下面继续看新的信息，这点非常便利实用，但是目前erark这个软件还实现不了这个效果，往上翻完了记录需要手动往下滚或者用鼠标拖动右侧滑动条，是否可以考虑增添类似的快速回底功能？
8：会考虑增加游戏内的debug功能或者开关吗，有类似的功能的话对于测试各种功能的运作和游戏体验的提升都会带来不少便利和好处。

以上，体验之后大概暂时想到的就这么多，这个游戏的框架还是搭建的很不错的，未来可期，希望作者继续加油！

**Comment by Kamisato100** [comment]
还有一些小bug，比如干员跟随无效，博士一直没法吃东西之类的

**Comment by Godofcong-1** [comment]
因为有很多条所以就按条回复，每条解决了就打个勾，打完全部的勾之前这个issue就先一直保留着
1.滑动条写好了，立绘的补充说明也加上了，增加数目具体是想要什么样的？比方说，一个文本框然后填一个数字进入，文本框的后面是一个确认键那样的？
2.嗯……应该可以做进基地的管理一览里
3.正常来说，角色默认都是用地文的，目前通用的地文数量还非常少，所以空白的地文就会显示一条'触发了XXX指令的地文'，如果是确认这个指令是有地文的，但是角色没有触发的话，那应该是BUG
4.如果只是为了测试用途的话，debug模式下有快速空白推进时间的指令，也有妊娠相关的测试功能，debug的开启方法是把 config.ini 文件里的debug从0改为1
5.干员AI应该是通用的，只要能正常在游戏里使用的话，应该就会沿用工作和娱乐的AI判断系统，如果不确定是什么问题的话可以把文件发给我康康_(:з」∠)_
6.唔，那我回头加个二次确认吧，避免手滑
7.这个稍微有点难度，我得想一下怎么实现
8.见4
9.跟随的问题有好多人反馈了，我复制一下之前的回答：同行的效果不好是设计上导致的问题，根本原因是现在的时间推进设计下，时间的前进和停止是以玩家的每次指令决定，导致因此NPC的行动总是会慢玩家一步，所以当玩家移动时，NPC虽然打算跟上，但她的下一步行动才是移动到玩家当前的位置。这个问题一直排在todo list里，只是现在手头上事情太多了还没来得及处理
10.角色吃东西是需要两个条件，一个是足够饿，一个是在饭点，如果满足这两个条件还没是不能吃的话那就是BUG了
