### ISSUE TITLE
有接入翻译的需求吗？

### ISSUE THREAD

**Issue by qwedc001** [Godofcong-1/erArk#41]
我看到入口文件上有跟i18n有关的内容，有考虑接入翻译的话，我可以帮忙中/英翻译
我接触过的平台有weblate和paratranz，可惜paratranz似乎不能再搞r18相关内容了

**Comment by Godofcong-1** [comment]
是有这个准备，不过原本是打算等游戏做个差不多再整这方面来着，没想到这才α测就有人愿意来翻译了，真是非常感谢！
以及现在discord的群里也有一个人也在打算做英翻来着，如果方便的话，要不要来discord群里和我以及那位看看怎么一起协力翻译，以及我能提供什么样的帮助？
