### ISSUE TITLE
一点小小的请求

### ISSUE THREAD

**Issue by Lu-zer** [Godofcong-1/erArk#43]
更新到3.1-1的版本之后，之前写的口上好像有好几条被和成一条了……光顾着修没有保存了，所以只是说一下。

关于口上编辑器，搜索的时候可以搜索触发口上的指令吗？还是说有根据指令分类的功能？
目前100多条还好，后面想要给之前写的指令添加更多情景的时候，寻找起来不太方便。
如果实现不了也没关系。

**Comment by Lu-zer** [comment]
又出现了
91,110,385,high_1&sys_0&love_ge_1（后面是口上）
92,110,385,high_1&sys_0&love_ge_2,（后面是口上）
93,110,385,high_1&sys_0&love_ge_3,（后面是口上）
94,111,385,high_1&sys_0&t_is_assistant,（后面是口上）
95,111,385,high_1&sys_0&not_in_dor,（后面是口上）
96,111,385,high_1&sys_0&not_in_dr_off,（后面是口上）
97,111,385,high_1&sys_0&t_is_assistant&love_ge_2,（后面是口上）
98,112,385,high_1&in_dor&not_fall&favorability_le_2,（后面是口上）
99,112,385,high_1&in_dor&not_fall&favorability_le_2,（后面是口上）
100,112,385,high_1&in_dor&love_ge_2,（后面是口上）
101,112,385,high_1&in_dor&love_ge_2,（后面是口上）
102,112,385,high_1&in_dor&love_ge_2&work_is_massage_therapist,（后面是口上）
103,112,385,high_1&in_dor&love_ge_3,（后面是口上）
上面还有，都是这样的格式，字符总长度没有到100，编辑器里面是正常的，一保存之后就会出现好几个口上粘在一起的情况。

**Comment by Lu-zer** [comment]
一个个改完之后完全没用……还是那么依托……81号到103号……心态有点炸裂

**Comment by Godofcong-1** [comment]
没事没事，有问题我这边都会修的，不要担心，你看我更新这么频繁就是在一直修各种方面的问题
合成一条，和口上粘在一起，具体指的是……？是说若干句口上的文本合在同一句了吗？还是说口上的编号发生了更改，原本不在一起，但是序号连在一起了？
以及如果你要的功能是只筛选特定指令的口上的话，现在的编辑器是有的，就是删除条目后面的那个勾选框，那个勾了之后就是字面意思的，只晒出当前选择指令的口上

**Comment by Lu-zer** [comment]
原本是分开来的，81号后面的口上连带着他们的编号都变成了81号口上的”口上“，格式就是上面那样
正常的81号口上后面接上了下面这个，后面格式都是一摸一样的
82,110,385,high_1&sys_0&t_is_assistant,“
保存的时候编辑器里显示都是正常的

**Comment by Lu-zer** [comment]
我看了下，不仅是文本，好像是序号、指令类型、这个385不知道是什么，还有触发条件，文本内容，都和81号的文本内容合并在一起了。
用到的指令是“休息”、“身体接触”、“睡觉”、“淋浴”。81号是休息指令。

**Comment by Lu-zer** [comment]
打开表格看了眼，81号的文本框里是后面口上的文本和编号那些，下一条就是104号了，中间没有其他的编号。

**Comment by Godofcong-1** [comment]
嗯……你把文件发一下我检查检查，看看是什么原因

**Comment by Lu-zer** [comment]
[385_铃兰.csv](https://github.com/Godofcong-1/erArk/files/14471498/385_.csv)
文档是吗？文笔有点差感觉有点羞耻的……

**Comment by Godofcong-1** [comment]
啊，我检查了一下，原因很简单，你在81行和103行里都打了一个英文小写双引号  "  ，把它删掉或者改成中文的就好了，我在编辑器里也加个判定，如果检测到这个符号就自动删除

**Comment by Lu-zer** [comment]
原来是这样的嘛……切输入法的时候没有注意……

**Comment by Lu-zer** [comment]
试了下久违的进游戏，结果完全触发不了口上，是权重的问题嘛？

**Comment by Lu-zer** [comment]
好像是铃兰的口上文件和属性文件编号不一样，都改成358之后也不行嘞……

**Comment by Lu-zer** [comment]
搞定了，原来要在编辑器里改，不过为什么铃兰口上文件编号和清流一样的嘞，都是385……

**Comment by Godofcong-1** [comment]
emmmm，铃兰是358，清流是385喔？

**Comment by Lu-zer** [comment]
原本不是有一点点口上吗？里面指令的ID是385（不是说铃兰是385，里面指令给的是385号）……因为太像了我反而没看见……（捂脸）

**Comment by Godofcong-1** [comment]
确实，那个文件里应该是写错了
