### ISSUE TITLE
Error - 食用食物的判断条件取反

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#48]
无崩溃报告
复现存档：
[9.zip](https://github.com/Godofcong-1/erArk/files/14842252/9.zip)
复现方式：进食任意特殊调味食物（只有在提示XX已经吃饱的情况下才能食用特殊调味食物，没有提示反而无法点击）
附注：我又回来辣——
手头还有个催眠相关的BUG（新版本到手就惦记你那俩催眠了.jpg），还有几个观测中的问题，晚点整理好了再拿Issues骚扰你
另，战斗要不要考虑做成类似卡牌游戏类型的模式（小队出击回合制行动之类的）
编辑（2024/4/3 2:29）：话说回来，以前我记得催眠进度不是能显示在名片后面来着，我个人作为催眠玩家还觉得那玩意儿挺好用的，能不能挪进设置可选项里

**Comment by Godofcong-1** [comment]
确实写反了，已修正
催眠进度的话，当时为了省空间删掉了，那我再加个到设置里好了

**Comment by Godofcong-1** [comment]
显示催眠进度的设置也加上了

**Comment by Godofcong-1** [comment]
看起来好久没有消息了，姑且先把这个关掉，有其他的问题就再发新的issue吧！
