### ISSUE TITLE
630版本H体力清零时出错 疑似bug复刻

### ISSUE THREAD

**Issue by shiramineS** [Godofcong-1/erArk#53]
![PixPin_2024-07-02_12-27-37](https://github.com/Godofcong-1/erArk/assets/127011696/2295b74e-aa34-4fbe-a5b3-c9ce445bb437)
[error.log](https://github.com/user-attachments/files/16061677/error.log)

**Comment by Godofcong-1** [comment]
是有个绝顶的结算没有定义，紧急推送了个6.30-1版本
