### ISSUE TITLE
7.3 感觉像数字爆了

### ISSUE THREAD

**Issue by shiramineS** [Godofcong-1/erArk#54]
[error.log](https://github.com/user-attachments/files/16089669/error.log)
![PixPin_2024-07-04_03-07-18](https://github.com/Godofcong-1/erArk/assets/127011696/ae47dc04-cc3a-4379-bca3-ed9265dc2758)

**Comment by Godofcong-1** [comment]
检查了一下，如果连续绝顶次数足够多可能会导致快感阈值降得过低，出现的这个BUG。7.4已修复
