### ISSUE TITLE
0101_空.csv存在bug，有可能造成filter error崩溃

### ISSUE THREAD

**Issue by okmmko** [Godofcong-1/erArk#61]
使用二分法确定了是空（而且只有空）的csv中存在的问题

在空的csv文件中，第二行“前面的类型里int则为0,str则为1”的逗号是英文逗号，造成csv异常分隔，可以在后续版本中把空csv的英文逗号改成中文逗号

**Comment by Godofcong-1** [comment]
确实，已修正
