### ISSUE TITLE
Warn&Error - 催眠相关按钮消失及其他催眠相关问题

### ISSUE THREAD

**Issue by TheXeler** [Godofcong-1/erArk#62]
异常描述：在有多个已被催眠的干员在场时，集体催眠和加深催眠分别因为各自的前提被隐藏了，导致两个选项同时不显示
附注：两个按钮夫妻双双把家还了（什）

**Comment by TheXeler** [comment]
另报告：目前的观测结果来看，该异常似乎和平然催眠相关，将默认催眠模式调整为体控后问题即消失
又及：额外报告四个小BUG/设计误差（就不开一堆Issues进行轰炸了.jpg）
一、集体催眠时会提示当前地点无法关门（单人催眠无此提示，而且催眠本身好像也不是那种会导致抓住把柄之类的行动）
二、催眠时如果提示你无法关门是否继续，选否仍然会导致催眠行动继续（怀疑这里代码和关门混了）
三、催眠时会显示催眠·浅、催眠·深和催眠·极的状态获得，但只会在200%时触发浅、深和极的判定（或者极指的就是催眠到200%后继续催眠一次？），并且如果不进入催眠状态就无法判定（但催眠度仍然会如常增加，举例为默认空气催眠但在不能关门的地方进行）
四、空气催眠为什么必须关门啊（恼），我全岛都200%催眠，不关门也敢啊（震声）
又及：一个建议，能不能在每个地方只问一次是否关门，文本可以写成类似：“接下来在此地点的催眠是否不关门，是/否”
又及：什么时候有战斗内容，你提个大概我帮你搭数值模型之类的也行啊（吉吉国王）

**Comment by TheXeler** [comment]
再次补充：多人时好像也没有对单人的解除催眠了

**Comment by TheXeler** [comment]
另：很久之前就想讲的，怎么没有返回主菜单

**Comment by TheXeler** [comment]
口上反馈：蓝毒代码中的博士代名词被误写成了干员代名词

**Comment by Godofcong-1** [comment]
> 再次补充：多人时好像也没有对单人的解除催眠了

也将其改为了，场景中没有其他有意识的人

**Comment by Godofcong-1** [comment]
> 另：很久之前就想讲的，怎么没有返回主菜单。误点到创建新游戏之后也不能返回

因为存读档不需要回到开始菜单，在游戏内就可以，所以就不需要回了，手滑了就重开罢（无慈悲）

**Comment by Godofcong-1** [comment]
> 口上反馈：蓝毒初见地文中的博士代名词被误写成了干员代名词

好，我反馈给口上作者

**Comment by TheXeler** [comment]
> 三：emmm，我没太理解，触发判定是什么意思……？是说触发获得该素质的地文吗？我测试了一下，50%也能触发获得催眠·浅素质的地文
我之前好像反馈过这个BUG，催眠必须到200%才会开始判定素质，集体催眠似乎仍然保留了一些原本的风味
另一个可能的猜测是：必须进入催眠状态才会开始判定素质（假设我催眠选择的默认形式是体控，那么在50%和100%时虽然已达到催眠·浅/深/极的要求，但是因为并未进入催眠状态所以不判定）
又及：集体催眠时即便中途甚至开头理智就因为施法清空了，还是会如常给所有人添加催眠进度和经验

**Comment by Godofcong-1** [comment]
> > 三：emmm，我没太理解，触发判定是什么意思……？是说触发获得该素质的地文吗？我测试了一下，50%也能触发获得催眠·浅素质的地文
> 
> 我之前好像反馈过这个BUG，催眠必须到200%才会开始判定素质，集体催眠似乎仍然保留了一些原本的风味 另一个可能的猜测是：必须进入催眠状态才会开始判定素质（假设我催眠选择的默认形式是体控，那么在50%和100%时虽然已达到催眠·浅/深/极的要求，但是因为并未进入催眠状态所以不判定） 又及：集体催眠时即便中途甚至开头理智就因为施法清空了，还是会如常给所有人添加催眠进度和经验
> 
> 修改：经验证，应该是因为催眠素质的判定必须进入催眠状态后才开始计算

判定获得催眠素质的BUG已修复

无理智进行集体催眠的BUG已修复
