### ISSUE TITLE
关于干员的服饰问题

### ISSUE THREAD

**Issue by 00590** [Godofcong-1/erArk#69]
因为确实默认服装看着终觉得怪怪的于是自己去尝试学了服设，然后某个笨（我）不会联系作者于是只好这样发出来了
（狗头保命
[惊蛰服饰考订.txt](https://github.com/user-attachments/files/16754954/default.txt)
）

**Comment by 00590** [comment]
如果可以的话，我会尝试把其他的（干员啊，口上啊）也写写（如果作者同意）

**Comment by Godofcong-1** [comment]
可以的，非常欢迎来补充角色的服装
以及可以直接用编辑器来写，里面有角色卡编辑模式，直接编辑原csv文件，不用再单独写txt文件啦

**Comment by 00590** [comment]
哇咔咔，我又回来啦
有一说一这次的真难考……好多根本查不到
所以勉勉强强，凑凑了下
令：方舟编辑器有BUG（什么叫先天BUG圣体啊，战术后仰.JPG）
我那该死的Windows自动更新后用方舟编辑器，它会把上一个读取的文件中角色的服饰一栏随即保留一项复制到新打开的文件，然后该角色（新打开文件的角色）其余服饰全部删除，只保留了复制过来的那一条（阿巴阿巴，这个bug重启和重装均不管用，估计是系统冲突了
[九色鹿服饰考订.txt](https://github.com/user-attachments/files/16765591/default.txt)
）

**Comment by 00590** [comment]
上一个文件有问题，这个是新的
[副本-九色鹿服饰考订.docx](https://github.com/user-attachments/files/16773582/-.docx)
