### ISSUE TITLE
报错？：把睡着的人拉去外勤，回来还是睡的

### ISSUE THREAD

**Issue by PhlilpAlapa** [Godofcong-1/erArk#71]
如何复现：
首先，2点，去外勤集合处，拉人去做时长为1天的外勤
然后，使用指令：等待5分钟
因为当天结算，所以委托会立刻完成，她们会被直接拉到入口1处
然后还是睡着的状态
因此是在梦游中完成的外勤吗hhhh
没错，这是两个不知道是BUG还是特性的东西

这个东西我还真不知道作者打算怎么处理。也不算恶性问题，当幽默特性也行

**Comment by PhlilpAlapa** [comment]
![屏幕截图 2024-09-07 212038](https://github.com/user-attachments/assets/061ceca9-03b9-433e-95db-2383211e7b71)醒来后更幽默了

**Comment by Godofcong-1** [comment]
9.9版本已修复
