### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by baqianmeng** [Godofcong-1/erArk#73]
[error.log](https://github.com/user-attachments/files/17172367/error.log)

**Comment by Godofcong-1** [comment]
9.29已修正，如果还有问题欢迎反馈

**Comment by baqianmeng** [comment]
[error.log](https://github.com/user-attachments/files/17256144/error.log)

**Comment by Godofcong-1** [comment]
从log里看好像还在使用9.26的旧版本，可以直接下个新版的，然后把存档文件夹拷过去就可以啦

**Comment by Godofcong-1** [comment]
因较长时间没有活跃了，所以将该issus暂时关闭，如果还有需求欢迎随时再打开
