### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Viteyun** [Godofcong-1/erArk#74]
### 场景
版本：2024.9.29-2
没注意怎么触发的，疑似是当时点击较快，名字没有输入就直接确认，后续直接就是空的
![QQ截图20241004235321](https://github.com/user-attachments/assets/04f91cae-0355-4dd1-9dbd-0cc056085a96)

![image](https://github.com/user-attachments/assets/8b84f583-ce3a-4866-b96c-e6aa4e0fca48)

## 2. 白金调教口上无限循环
版本：2024.9.30-1
![image](https://github.com/user-attachments/assets/118e890a-f004-43bd-b994-3ccaca09b6e5)

## 3.一个未知bug
版本：2024.9.30-1
突然在处理公务时弹出
[error.log](https://github.com/user-attachments/files/17266698/error.log)

**Comment by Godofcong-1** [comment]
女儿命名错误的BUG：已修复
白金角色事件死循环的BUG：已临时处理为不会触发跳过，具体等口上作者来调整
处理公务的BUG：原因不太好判断，可能需要提供一下报错当时的99号存档

**Comment by Godofcong-1** [comment]
new：处理公务的BUG可能是这个issus里反馈的调香师的口上导致的 https://github.com/Godofcong-1/erArk/issues/75#issue-2577729815

**Comment by Viteyun** [comment]
又一个报错，但也无法确定是不是这个导致的报错
这个是执行亲吻操作报的
版本：2024.10.12-1
[99.zip](https://github.com/user-attachments/files/17350556/99.zip)
[error.log](https://github.com/user-attachments/files/17350557/error.log)

（不小心点歪了，点到close，我是怎么歪的这么离谱的23333）

**Comment by Godofcong-1** [comment]
> 又一个报错，但也无法确定是不是这个导致的报错 这个是执行亲吻操作报的 版本：2024.10.12-1 [99.zip](https://github.com/user-attachments/files/17350556/99.zip) [error.log](https://github.com/user-attachments/files/17350557/error.log)
> 
> （不小心点歪了，点到close，我是怎么歪的这么离谱的23333）

感谢反馈，已修复
