### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by daxuananwei** [Godofcong-1/erArk#75]
`data/talk/chara/0181_调香师.csv`

cid 34行 high_1&place_0&CVP_A3|181__E_2   181和E之间有两个连续的下划线

9.30-1版本还发现助理人物会重复behavior_id=2的动作，一直到人物体力耗尽原地睡觉，触发条件不明，新版本还没测试

**Comment by Godofcong-1** [comment]
感谢反馈，调香师的BUG已修正
助理的这个BUG的话，可能需要提供一下出现这种情况当时的存档来找一下原因

**Comment by Godofcong-1** [comment]
emmm，助理的晚安问候是选的催睡觉还是其他的两个？

**Comment by Godofcong-1** [comment]
> [25.zip](https://github.com/user-attachments/files/17341143/25.zip) 是10.10的新档， 助理 调香师 跟随 智能 辅佐 是 送饭 亲手 早安 叫起床 晚安 催睡觉 同居 否 助攻 否

10.12-1已修正，在该存档下，博士当天晚上睡觉后会重置也同样在睡觉的调香师的晚安问候flag，第二天即可恢复正常
