### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by HuangHico** [Godofcong-1/erArk#76]
[error.log](https://github.com/user-attachments/files/17378462/error.log)
一移动就崩溃，看了一眼log怀疑是对话模块导致的

**Comment by HuangHico** [comment]
[error.log](https://github.com/user-attachments/files/17378477/error.log)

**Comment by Godofcong-1** [comment]
已推送10.15-1修复该问题

**Comment by Godofcong-1** [comment]
因较长时间没有活跃了，所以将该issus暂时关闭，如果还有问题欢迎随时再打开
