### ISSUE TITLE
在白金的睡jian中依然会显示清醒时的地文

### ISSUE THREAD

**Issue by satan0910** [Godofcong-1/erArk#77]

**Comment by Godofcong-1** [comment]
请问方便提供当时的存档吗

**Comment by Godofcong-1** [comment]
测试了一下，在邀请H的时候会有清醒文本出现，还有其他的指令会有清醒文本吗

**Comment by satan0910** [comment]
另外发现白金排卵的地文频繁出现

**Comment by baqianmeng** [comment]
[error.log](https://github.com/user-attachments/files/17528756/error.log)
基本玩不了了

**Comment by Godofcong-1** [comment]
> 另外发现白金排卵的地文频繁出现

已向白金作者传达该情况，请问可以麻烦提供一下截图吗

**Comment by Godofcong-1** [comment]
> [error.log](https://github.com/user-attachments/files/17528756/error.log) 基本玩不了了

您是半个月前的那个issus的楼主吧，我看了一下您的log，还是没有更新版本，可以麻烦您更新一下新版本试一下吗？

**Comment by satan0910** [comment]
![image](https://github.com/user-attachments/assets/30bee113-6d4f-45df-a4fa-d8903b591941)
基本每一天进入H模式时都会触发此地文，触发后润滑+10k，有次每个动作都会使润滑+10k，但后来没有复现
另外正常动作不会使体力归零，请问是正常的吗

**Comment by Godofcong-1** [comment]
> ![image](https://private-user-images.githubusercontent.com/185498541/380390593-30bee113-6d4f-45df-a4fa-d8903b591941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNjkzMTcsIm5iZiI6MTczMDE2OTAxNywicGF0aCI6Ii8xODU0OTg1NDEvMzgwMzkwNTkzLTMwYmVlMTEzLTZkNGYtNDVkZi1hNGZhLWQ4OTAzYjU5MTk0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwMjMwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDFjNDIzM2YxYTJjZDQxOTdmMjNkNTQ1MDIzNDFkOTQ4OTJkNTU3MGE2ZTI1YTU3Mzg4Y2QxOTExYTY3ODI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1AD269x-8jBCi0y8clFYiVQ_HhN4VyyNDYEeh09FboE) 基本每一天进入H模式时都会触发此地文，触发后润滑+10k，有次每个动作都会使润滑+10k，但后来没有复现 另外正常动作不会使体力归零，请问是正常的吗

已反馈给白金口上作者
正常动作是指非H类的，其他类型的指令吗
体力都是会最小锁到1的，H下体力1的时候会退出H，然后NPC进入疲劳状态回去睡觉
非H下体力1的时候，NPC会直接进入疲劳状态回去睡觉
