### ISSUE TITLE
访客干员行为异常

### ISSUE THREAD

**Issue by assassingyk** [Godofcong-1/erArk#80]
目前版本访客干员到来后就停留在访客区内走廊不动了，也不吃饭也不睡觉）
邀请同行后可以跟着走一段，但是只要一互动就会自动返回访客区内走廊
![image](https://github.com/user-attachments/assets/82ea10e0-2a94-4f80-bf95-7f55cfcde6c2)

**Comment by Godofcong-1** [comment]
应该是访客的AI异常，可以麻烦提供一下当时的存档吗

**Comment by assassingyk** [comment]
[1.zip](https://github.com/user-attachments/files/17530638/1.zip)

**Comment by Godofcong-1** [comment]
检查了一下，原因是因为访客上岛的时候分配了错误的房间导致的，已修正了房间分配的函数，之后上岛的访客应该都正常了
现在的档的话，可以考虑把访客区的等级拉高，把全客房解锁，访客就能正常回到房间里了
