### ISSUE TITLE
自动存档问题

### ISSUE THREAD

**Issue by assassingyk** [Godofcong-1/erArk#82]
auto栏位的自动存档似乎存档的游戏内时间是醒来后，但游戏状态是睡眠结算前，理智什么的虽然计算了休息的恢复量但没有结算提升，助理也会卡在催睡觉的状态……
![image](https://github.com/user-attachments/assets/91a68410-a596-4ef9-bc1c-a08aa28c76bb)

**Comment by Godofcong-1** [comment]
todo插眼
