### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by assassingyk** [Godofcong-1/erArk#83]
最近几天发现的一部分小问题，就一起发了）

1. 阴〇夹/乳〇夹和跳蛋选项好像不加C/B经验？调教半天发现感度不涨才发现，不知道是有意还是无意的）

2. 属性升级的条件能否参考其他ERA提供多种选择？例如提升顺从等级除了消耗默认的恭顺珠也可以选择消耗更多的屈服珠或者恐怖珠来提升。

3. H中的交给对方选项似乎有几率随机出消耗库存不足物品的选项？我现在有负数个灌肠液）
![image](https://github.com/user-attachments/assets/a8d569ee-5289-40c7-b1ff-8368fa299554)

4. H中体力不足中断时的寸止结果好像没有结算？就是虽然显示了多重绝顶但数据并没有体现出来，也触发不了刻印）

5. [切换催眠模式]选项似乎可以无视对面实际催眠等级进行执行？
![image](https://github.com/user-attachments/assets/e531697f-bf72-46c2-8057-4e0bae1807bb)
![image](https://github.com/user-attachments/assets/5ab7a857-1099-4286-a8e2-6be7ecd5f639)

**Comment by Godofcong-1** [comment]
> 1. 阴〇夹/乳〇夹和跳蛋选项好像不加C/B经验？调教半天发现感度不涨才发现，不知道是有意还是无意的）

已修正
> 2. 属性升级的条件能否参考其他ERA提供多种选择？例如提升顺从等级除了消耗默认的恭顺珠也可以选择消耗更多的屈服珠或者恐怖珠来提升。

拉数值曲线挺麻烦的，所以这个就先搁置了
> 3. H中的交给对方选项似乎有几率随机出消耗库存不足物品的选项？我现在有负数个灌肠液）

理论上来讲H中的逆推应该是跳过消耗道具类指令的，如果触发了那确实是BUG，我这边简单测试了一下但是没复现出来，下次如果出现的话可以存个档我看看原因
> 4. H中体力不足中断时的寸止结果好像没有结算？就是虽然显示了多重绝顶但数据并没有体现出来，也触发不了刻印）

todo
> 5. [切换催眠模式]选项似乎可以无视对面实际催眠等级进行执行？

已修正

**Comment by Godofcong-1** [comment]
因较长时间没有活跃了，所以将该issus暂时关闭，如果还有问题欢迎随时再打开
