### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by baqianmeng** [Godofcong-1/erArk#85]
大佬不会更新 能教一下吗 我是code-https-download zip-解压这样有问题吗 我是从其他人那里下载的 里面有game.exe直接能玩 现在下载的进去全是错误玩不了

**Comment by Viteyun** [comment]
右边有个Release，那个是已经发布的版本，找最新的下载
![image](https://github.com/user-attachments/assets/3df91f10-35d2-44e5-ac59-9b293c777b77)
第一个是编辑器
第二个是编译好的游戏文件夹，点game.exe就行
第三个是字体文件，推荐是安装一下

**Comment by Viteyun** [comment]
> 大佬不会更新 能教一下吗 我是code-https-download zip-解压这样有问题吗 我是从其他人那里下载的 里面有game.exe直接能玩 现在下载的进去全是错误玩不了

右边有个Release，那个是已经发布的版本，找最新的下载
![image](https://github.com/user-attachments/assets/3df91f10-35d2-44e5-ac59-9b293c777b77)
第一个是编辑器
第二个是编译好的游戏文件夹，点game.exe就行
第三个是字体文件，推荐是安装一下

我推荐是你把错误截个图，或者把错误信息发上来，不然不好判断的

**Comment by baqianmeng** [comment]
[error.log](https://github.com/user-attachments/files/17606551/error.log)
OK 这下载速度怎么能提升一下吗

**Comment by baqianmeng** [comment]
大佬这个游戏存档怎么修改 想改一下粉红凭证 还有这个人物现在太多了 有没有一种能把他们请离 以后还能招募的那种功能

**Comment by Godofcong-1** [comment]
> 大佬这个游戏存档怎么修改 想改一下粉红凭证 还有这个人物现在太多了 有没有一种能把他们请离 以后还能招募的那种功能

在`config.ini`中将debug改为1即可开启debug模式
修改前请备份存档，避免数据修改错误导致坏档

解聘干员功能目前还没有，之后抽空写一下吧
