### ISSUE TITLE
未知问题

### ISSUE THREAD

**Issue by Viteyun** [Godofcong-1/erArk#86]
版本：2024.10.31-1
一个问题，没有输出错误日志，也没有自动保存，已经多次触发，事件包括但不限于，对话，移动，处理公事
界面没有输出完，直接卡主。后台的控制台输出了这样的信息
![image](https://github.com/user-attachments/assets/c439607e-6a0c-4985-9dd5-309ab6a2a254)

更正，基本确定是蓝毒的问题了，然后还遇到一个bug，已经上岛的干员，怎么突然作为访客又来了一次2333

**Comment by Godofcong-1** [comment]
蓝毒的图像BUG在10.30-2版本中已修正
访客的话可能需要提供一下存档来看看发生的原因

**Comment by Viteyun** [comment]
> 蓝毒的图像BUG在10.30-2版本中已修正 访客的话可能需要提供一下存档来看看发生的原因

复现了，正好在做外勤任务，会不会是这个原因？
![image](https://github.com/user-attachments/assets/d7878330-cea5-4492-8209-dd83210c8178)

[0.zip](https://github.com/user-attachments/files/17707706/0.zip)

**Comment by Godofcong-1** [comment]
> > 蓝毒的图像BUG在10.30-2版本中已修正 访客的话可能需要提供一下存档来看看发生的原因
> 
> 复现了，正好在做外勤任务，会不会是这个原因？

感谢反馈，11.15已修复，如果还有问题欢迎继续反馈
