### ISSUE TITLE
README中的Discord邀请链接过期了

### ISSUE THREAD

**Issue by Slintchen** [Godofcong-1/erArk#87]
README中的Discord邀请链接过期了，求一个新的链接，想进群看看

**Comment by Godofcong-1** [comment]
> README中的Discord邀请链接过期了，求一个新的链接，想进群看看

检查了一下，链接没有过期，可以正常使用，再试一下？

**Comment by Slintchen** [comment]
![image](https://github.com/user-attachments/assets/e2799876-8afe-45eb-aa65-ec229791081b)
QwQ

**Comment by Godofcong-1** [comment]
emmm，那我就不太清楚了……但确实是可以用的，现在也时不时有人通过这个链接进来

**Comment by Slintchen** [comment]
那就怪了，我人是在国外的，不太可能是网络环境的问题

**Comment by Slintchen** [comment]
嗷，确认了，是网页版discord抽风的问题，我复制到客户端然后添加服务器就能正常加入了。非常抱歉这么笨的问题还打扰到您了
