### ISSUE TITLE
进入H后无可用选项

### ISSUE THREAD

**Issue by assassingyk** [Godofcong-1/erArk#88]
如题，进入H后除了切换催眠模式选项外没有任何可用选项，连结束H的选项都没有，全部分类打开关闭都试过了也没变化，H界面也没有存读档，直接卡死了（）
![image](https://github.com/user-attachments/assets/f4a9225a-9d1d-4ed6-bdd2-8ac281718878)

**Comment by Godofcong-1** [comment]
紧急推送了11.6-2版本解决该问题
