### ISSUE TITLE
游戏进行到14点25会卡死

### ISSUE THREAD

**Issue by NaricaNardica** [Godofcong-1/erArk#90]
选取额外初始干员为斯卡蒂+W+红蒂

**Comment by NaricaNardica** [comment]
附存档文件
[5.zip](https://github.com/user-attachments/files/17690057/5.zip)

**Comment by whitephantom047** [comment]
游戏进行到19点左右会卡死，额外初始干员L2、夜刀、杜林，附存档文件
[1.zip](https://github.com/user-attachments/files/17699060/1.zip)

**Comment by Godofcong-1** [comment]
感谢反馈，推送了11.11版本解决该问题
原存档更新到新版本后部分干员角色可能会在原地停住不动一段时间，理论上第二天应该会恢复正常

**Comment by Godofcong-1** [comment]
因较长时间没有活跃了，所以将该issus暂时关闭，如果还有问题欢迎随时再打开
