### ISSUE TITLE
游戏卡死：队列在不停的增加信息

### ISSUE THREAD

**Issue by xilq** [Godofcong-1/erArk#91]
现象是与阿米娅在办公室，点击处理公务，然后游戏卡死不动。我进源码看了下发现是main_queue在不断的输出空的文本信息。
![image](https://github.com/user-attachments/assets/aaddf1d0-eeeb-4839-a5d7-bbfe136825de)
这个存档基本是稳定复现。
[Uploading 2.zip…]()

**Comment by Godofcong-1** [comment]
emmm……存档好像没传上来，点击之后跳转到这个issue了

**Comment by xilq** [comment]
[2.zip](https://github.com/user-attachments/files/17709119/2.zip)

**Comment by Godofcong-1** [comment]
看上去是和 https://github.com/Godofcong-1/erArk/issues/90 同样的原因，昨天推的11.11版本已修复，如果还有问题欢迎随时反馈
