### ISSUE TITLE
未知原因报错

### ISSUE THREAD

**Issue by bluesky9988** [Godofcong-1/erArk#93]
这边进入h场景后，不管做啥都会出现这图一样的代码报错。
![Image_12312650556117](https://github.com/user-attachments/assets/908604dd-50e7-45df-8d3e-e1f222035bb2)

**Comment by Godofcong-1** [comment]
请问是有修改过游戏数据吗，从log来看有可能是改数据导致坏档了，如果有备份的修改前的存档的话，回到原存档应该就正常了

**Comment by bluesky9988** [comment]
> 请问是有修改过游戏数据吗，从log来看有可能是改数据导致坏档了，如果有备份的修改前的存档的话，回到原存档应该就正常了

用过debug，但是不知道是哪个数据的修改导致的，改的比较多。有哪些存完上限的修改项么？

**Comment by Godofcong-1** [comment]
> 用过debug，但是不知道是哪个数据的修改导致的，改的比较多。有哪些存完上限的修改项么？

大概有一半左右的数据是有上限的
角色部分的数据的话，可以在游戏文件夹中的 `data\csv` 里查询对应数据的数值上限
非角色部分可以查看源码中的 `Script\Core\game_type.py` 文件来寻找数据的上限

**Comment by bluesky9988** [comment]
> > 用过debug，但是不知道是哪个数据的修改导致的，改的比较多。有哪些存完上限的修改项么？
> 
> 大概有一半左右的数据是有上限的 角色部分的数据的话，可以在游戏文件夹中的 里查询对应数据的数值上限 非角色部分可以查看源码中的 文件来寻找数据的上限`data\csv``Script\Core\game_type.py`

谢谢

**Comment by bluesky9988** [comment]
> > 用过debug，但是不知道是哪个数据的修改导致的，改的比较多。有哪些存完上限的修改项么？
> 
> 大概有一半左右的数据是有上限的 角色部分的数据的话，可以在游戏文件夹中的 里查询对应数据的数值上限 非角色部分可以查看源码中的 文件来寻找数据的上限`data\csv``Script\Core\game_type.py`

不过script这个文件夹到底在解压文件里压根找不到，请问一般会在哪个位置，搜索都搜不到

**Comment by bluesky9988** [comment]
> > 用过debug，但是不知道是哪个数据的修改导致的，改的比较多。有哪些存完上限的修改项么？
> 
> 大概有一半左右的数据是有上限的 角色部分的数据的话，可以在游戏文件夹中的 里查询对应数据的数值上限 非角色部分可以查看源码中的 文件来寻找数据的上限`data\csv``Script\Core\game_type.py`

另外求问大佬怎么改数据能加大射精量

**Comment by Godofcong-1** [comment]
> > 大概有一半左右的数据是有上限的 角色部分的数据的话，可以在游戏文件夹中的 里查询对应数据的数值上限 非角色部分可以查看源码中的 文件来寻找数据的上限`` data\csv``Script\Core\game_type.py ``
> 
> 不过script这个文件夹到底在解压文件里压根找不到，请问一般会在哪个位置，搜索都搜不到

源码指的是源代码，也就是该项目的代码，不是游戏内的文件，可以通过在线查看项目或下载项目到本地后查看

> 另外求问大佬怎么改数据能加大射精量

射精相关的结算在源码的 `Script\UI\Panel\ejaculation_panel.py`
更改后可直接运行 `game.py` 或参考 `.github\workflows\python-app.yml` 编译为exe后运行

**Comment by Godofcong-1** [comment]
因较长时间没有活跃了，所以将该issus暂时关闭，如果还有问题欢迎随时再打开
