### ISSUE TITLE
在训练室射击崩溃了

### ISSUE THREAD

**Issue by PNaClNH3** [Godofcong-1/erArk#96]
[save.zip](https://github.com/user-attachments/files/17921497/save.zip)

**Comment by Godofcong-1** [comment]
检查了一下存档，暂时没有发现问题，需要麻烦发一下崩溃时的报错log，应该在游戏的根目录下，名字是error.log

**Comment by Godofcong-1** [comment]
感谢反馈，11.28已修正

**Comment by Godofcong-1** [comment]
因较长时间没有活跃了，所以将该issus暂时关闭，如果还有问题欢迎随时再打开
