### ISSUE TITLE
角色预设的文本在游戏里看不到，已开启通用+专属文本显示

### ISSUE THREAD

**Issue by HeiMi23** [Godofcong-1/erArk#97]
RT,截至11/27的版本，游戏里角色预设的文本，在主游戏里无显示，比较明显的就是U-official的文本，目前游戏里互动时只有通用文本

**Comment by Godofcong-1** [comment]
> RT,截至11/27的版本，游戏里角色预设的文本，在主游戏里无显示，比较明显的就是U-official的文本，目前游戏里互动时只有通用文本

尤里卡现在的文本量相对还较少，指令覆盖也较少，可以看看文本量较多的白金是否有正常触发，如果白金也没有触发任何角色专属文本的话那就是BUG了

**Comment by Godofcong-1** [comment]
因较长时间没有活跃了，所以将该issus暂时关闭，如果还有问题欢迎随时再打开
