### ISSUE TITLE
可以设置个同类地文触发次数限制

### ISSUE THREAD

**Issue by gelanpoint** [Godofcong-1/erArk#98]
![345dd7c4-904f-4361-a287-ad7ebafd5ac2](https://github.com/user-attachments/assets/253ee166-b8e1-49c0-90ba-8cedaf2dd511)
如果干员处在跟随状态或者玩家与干员的目的地相同的情况下，每次去到一个新地点就会重新出发一次偶遇地文，有点奇怪。可以给此类地文加个触发前提——本日内未触发该地文时，或者加个每日限定触发一次的限制再或者是限制只有时隔多少个小时才可以再次触发此类地文

**Comment by Godofcong-1** [comment]
请问您那边的游戏版本号是多少？

**Comment by gelanpoint** [comment]
> 请问您那边的游戏版本号是多少？

玩过的所有版本都有此类问题，当时玩的记得没错的话是最新版来着

**Comment by Godofcong-1** [comment]
> 玩过的所有版本都有此类问题，当时玩的记得没错的话是最新版来着

这样的话，麻烦您试一下当前的版本里是否还有该问题，如果依然存在的话，可能需要提供一下存档方便复现

**Comment by gelanpoint** [comment]
> > 玩过的所有版本都有此类问题，当时玩的记得没错的话是最新版来着
> 
> 这样的话，麻烦您试一下当前的版本里是否还有该问题，如果依然存在的话，可能需要提供一下存档方便复现

[1.zip](https://github.com/user-attachments/files/18052645/1.zip)

**Comment by Godofcong-1** [comment]
> ；还是有，在存档里一个比较简单的触发方式：设置助理跟随，选择查看干员位置，自己前去干员位置，选择特雷西亚

感谢反馈，12.9中已修正该问题

**Comment by Godofcong-1** [comment]
因较长时间没有活跃了，所以将该issus暂时关闭，如果还有问题欢迎随时再打开
