### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by baqianmeng** [Godofcong-1/erArk#99]
[error.log](https://github.com/user-attachments/files/18048512/error.log)
我记得之前有个寸止的选项 现在没有了么

**Comment by Godofcong-1** [comment]
> [error.log](https://github.com/user-attachments/files/18048512/error.log) 

https://github.com/Godofcong-1/erArk/issues/93#issue-2661175487
从log来看，应该是和该issue一样是因为修改数据导致的

> 我记得之前有个寸止的选项 现在没有了么

现在也是有的

**Comment by Godofcong-1** [comment]
因较长时间没有活跃了，所以将该issus暂时关闭，如果还有问题欢迎随时再打开
